from selenium.webdriver.common.by import By


class APIMonitor:
    MONITOR = 'api/monitor'
    SUPER_USER = (By.XPATH, '//td[(text()="dbadmin")]')
    ADMIN = (By.XPATH, '//td[(text()="login12")]')
    EXPERT = (By.XPATH, '//td[(text()="login12_ex")]')
    LOAD = (By.XPATH, '//td[(text()="login12_load")]')
    LOGOUT = (By.CSS_SELECTOR, '[target="_blank"]')


class TopBars:
    DATA_BAR = (By.CSS_SELECTOR, '#header-menu__data')
    ANALYTIC_BAR = (By.CSS_SELECTOR, '#header-menu__analytics')
    TOOLS_BAR = (By.CSS_SELECTOR, '#header-menu__tools')
    ADMIN_BAR = (By.CSS_SELECTOR, '#header-menu__administration')
    REPORT_BAR = (By.CSS_SELECTOR, '#header-menu__reports')
    VIEW_BAR = (By.CSS_SELECTOR, '#header-menu__views')
    SEARCH_BAR = (By.CSS_SELECTOR, '#header-menu__search')
    RIGHT_BAR = (By.CSS_SELECTOR, '#header-menu__prop-menu')
    RIGHT_BAR_LOAD = (By.CSS_SELECTOR, '.bar.bar__right > li')
    USER_STATUS = (By.CSS_SELECTOR, '.d-flex.flex-column > span:nth-child(2)')
    EXIT_BUTTON = (By.CSS_SELECTOR, '#header-menu__logout')
    DROP_BLOCK_DEVICES = (By.CSS_SELECTOR, '#header-menu__data-devices')
    DROP_BLOCK_WORKSPACE = (By.CSS_SELECTOR, '#header-menu__analytics-workspace')
    DROP_BLOCK_DICTIONARIES = (By.CSS_SELECTOR, '#header-menu__tools-dictionaries')
    DROP_BLOCK_TEXT_ANALYZER = (By.CSS_SELECTOR, '#header-menu__analytics-analyzer')
    DROP_BLOCK_STATISCTICS = (By.CSS_SELECTOR, '#header-menu__administration-stat')
    DROP_BLOCK_LOAD_IMAGES = (By.CSS_SELECTOR, 'header-menu__data-queue-devices')


class Notifications:
    BLUE_NOTIFI = (By.CSS_SELECTOR, '#notification-info-1')
    BLUE_NOTIFI_2 = (By.CSS_SELECTOR, '#notification-info-2')
    BLUE_NOTIFI_3 = (By.CSS_SELECTOR, '#notification-info-3')
    BLUE_NOTIFI_4 = (By.CSS_SELECTOR, '#notification-info-4')
    NOTIFI_CLOSE = (By.CSS_SELECTOR, '#notification-info-1 > div > div.notification__close')
    NOTIFI_CLOSE_2 = (By.CSS_SELECTOR, '#notification-info-2 > div > div.notification__close')
    NOTIFI_CLOSE_3 = (By.CSS_SELECTOR, '#notification-info-3 > div > div.notification__close')
    NOTIFI_CLOSE_4 = (By.CSS_SELECTOR, '#notification-info-4 > div > div.notification__close')
    RED_NOTIFI = (By.CSS_SELECTOR, '#notification-danger-1')
    RED_NOTIFI_2 = (By.CSS_SELECTOR, '#notification-danger-2')
    RED_NOTIFI_3 = (By.CSS_SELECTOR, '#notification-danger-3')
    RED_NOTIFI_CLOSE = (By.CSS_SELECTOR, '#notification-danger-1 > div > div.notification__close')
    RED_NOTIFI_CLOSE_2 = (By.CSS_SELECTOR, '#notification-danger-2 > div > div.notification__close')
    RED_NOTIFI_CLOSE_3 = (By.CSS_SELECTOR, '#notification-danger-3 > div > div.notification__close')
    IMAGE_UPLOAD = (By.CSS_SELECTOR, '.notification > div:nth-child(2)')
    IMAGE_UPLOAD_PROCESS = (By.CSS_SELECTOR, '.notification > div:nth-child(3)')
    PRELOADER = (By.CSS_SELECTOR, '.preloader__main')


class CasesLocators:
    # не использовать без дела
    OPEN_BUTTON = (By.CSS_SELECTOR, '.button-open')
    ADD_CASE_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    TEST_CASE_1 = (By.XPATH, '//span[(text()="Auto_test_case")]')
    TEST_CASE_2 = (By.XPATH, '//span[(text()="Auto_test_case1")]')
    TEST_CASE_3 = (By.XPATH, '//span[(text()="Auto_test_case2")]')
    DB_CASE = (By.XPATH, '//span[(text()="IOS")]')
    SEARCH = (By.CSS_SELECTOR, '#search')
    COUNTER = (By.CSS_SELECTOR, '.row.grid-mb-16px > div > h1')
    BUTTON_SEARCH = (By.CSS_SELECTOR, '.grid-full-width')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar-filters > div > .btn.btn-primary')
    ADD_SECTION = (By.CSS_SELECTOR, '.modal-header')
    REGIONS_DROPDOWN = (By.CSS_SELECTOR, '[formcontrolname="region"] > div > .filter__button-outer')
    REGION_1ST = (By.CSS_SELECTOR, 'app-filter-search-backend-drop-menu > div > ul > li')
    CRIME_TYPES_DROPDOWN = (By.CSS_SELECTOR, '[formcontrolname="crimeType"] > div > .filter__button-outer')
    CRIME_1ST = (By.CSS_SELECTOR, 'app-filter-search-backend-drop-menu > div > ul > li')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    CANCEL_BUTTON = (By.CSS_SELECTOR, '.modal-footer.justify-content-end > button')
    RIGHT_SIDEBAR_DEVICE_TAB = (By.CSS_SELECTOR, '[role="tablist"] > li:nth-child(2)')
    RIGHT_SIDEBAR_TAB_DEVICE_1ST = (By.CSS_SELECTOR, '.kit__content_fixed-height-sm > label > span > span:nth-child(2)')
    RIGHT_SIDEBAT_DEVICE_COUNTER = (By.CSS_SELECTOR, '.justify-content-between > div > p')


class DevicesLocators:
    OPEN_BUTTON = (By.CSS_SELECTOR, '.button-open')
    EDIT_ACCEPT_BUTTON = (By.CSS_SELECTOR, '.justify-content-between > div > div')
    COUNTER_SECTION = (By.CSS_SELECTOR, '.typography__header--extra-large')
    SEARCH = (By.CSS_SELECTOR, '#search')
    GRID_DEVICE_NAME = (By.CSS_SELECTOR, '[data-uuid="alias"]')
    SELECTED_LINE = (By.CSS_SELECTOR, '.table__row--selected')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')
    BASKET_OK_BUTTON = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    CONFIRM_DELETE = (By.CSS_SELECTOR, 'app-popup-confirm-to-remove-device')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, 'app-popup-confirm-to-remove-device > div > div .btn.btn-danger')
    RIGHT_SIDEBAR_DEVICE_NAME_INPUT = (By.CSS_SELECTOR, '[name="deviceName"]')
    RIGHT_SIDEBAR_DEVICE_NAME = (By.CSS_SELECTOR, '.grid-full-width > h1')


class RegionsLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    REGION_NAME = (By.CSS_SELECTOR, '#name')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    SEARCH = (By.CSS_SELECTOR, '#search')
    GRID_REGION = (By.CSS_SELECTOR, '[data-uuid="name"]')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    RIGHT_SIDEBAR_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p')
    RIGHT_SIDEBAR_NOCASES = (By.CSS_SELECTOR, '.tab-content > div > div')
    RIGHT_SIDEBAR_REGION_NAME = (By.CSS_SELECTOR, '.grid-pr-20px > h1')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar-filters > div > .btn.btn-primary')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')


class CrimeTypesLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    CRIME_TYPE_NAME = (By.CSS_SELECTOR, '#name')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    SEARCH = (By.CSS_SELECTOR, '#search')
    GRID_CRIME_TYPE = (By.CSS_SELECTOR, '[data-uuid="name"]')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    RIGHT_SIDEBAR_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p')
    RIGHT_SIDEBAR_NOCASES = (By.CSS_SELECTOR, '.tab-content > div > div')
    RIGHT_SIDEBAR_CRIME_TYPE_NAME = (By.CSS_SELECTOR, '.grid-pr-20px > h1')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar-filters > div > .btn.btn-primary')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')


class LoadImagesLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    ADD_SECTION = (By.CSS_SELECTOR, '.modal-header')
    INPUT_FILE_OFBX_OFBR = (By.CSS_SELECTOR, '#fileDropRef')
    INPUT_FILE_ODB = (By.CSS_SELECTOR, '#fileDropRefODB')
    INPUT_FILE_Z = (By.CSS_SELECTOR, '#fileDropRefZ01')
    INPUT_FILE_UFD = (By.CSS_SELECTOR, '#fileDropRefUFD')
    INPUT_FILE_XRY = (By.CSS_SELECTOR, '#fileDropRefXRY')
    INPUT_FILE_PST_OST = (By.CSS_SELECTOR, '#fileDropRefPST')
    CHECKBOX_NOFILES = (By.CSS_SELECTOR, '[for="noFiles"] > span')
    BUTTON_ODB = (By.CSS_SELECTOR, '.col-4.pr-0 > ul > li:nth-child(2)')
    BUTTON_UFD = (By.CSS_SELECTOR, '.col-4.pr-0 > ul > li:nth-child(3)')
    BUTTON_XRY = (By.CSS_SELECTOR, '.col-4.pr-0 > ul > li:nth-child(4)')
    BUTTON_PST_OST = (By.CSS_SELECTOR, '.col-4.pr-0 > ul > li:nth-child(5)')
    CASES_LIST = (By.CSS_SELECTOR, '#case')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    CLOSE_BUTTON = (By.CSS_SELECTOR, '.btn.btn-outline-primary')
    GRID_1ST_ROW = (By.CSS_SELECTOR, 'tbody > tr')
    GRID_NOTIFI = (By.CSS_SELECTOR, 'tbody > tr > td:nth-child(7) > '
                                    'app-table-cell-renderer > app-grid-device-queue-msg > span')
    UPLOAD_BADGE = (By.CSS_SELECTOR, '[data-uuid="status"]')
    NO_RESULTS = (By.CSS_SELECTOR, 'tbody > tr > td > div')
    OFBX = (By.XPATH, '//span[(text()="ofbx")]')
    OFBR = (By.XPATH, '//span[(text()="ofbr")]')
    ODB = (By.XPATH, '//span[(text()="odb")]')
    UFED = (By.XPATH, '//span[(text()="zip")]')
    XRY = (By.XPATH, '//span[(text()="xry")]')
    PST = (By.XPATH, '//span[(text()="pst")]')
    OST = (By.XPATH, '//span[(text()="ost")]')


class HashesLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    OPEN_BUTTON = (By.CSS_SELECTOR, '.button-open')
    HASH_NAME = (By.CSS_SELECTOR, '#name')
    HASH_NOTE = (By.CSS_SELECTOR, '#note')
    HASH_UPLOAD = (By.CSS_SELECTOR, '#fileDropRef')
    HASH_TYPE = (By.CSS_SELECTOR, '#type')
    HASH_EXPORT = (By.CSS_SELECTOR, '.modal-footer.justify-content-end > button:nth-child(2)')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    SEARCH = (By.CSS_SELECTOR, '#search')
    GRID_HASH = (By.CSS_SELECTOR, '[data-uuid="name"]')
    GRID_HASH_TYPE = (By.CSS_SELECTOR, '[data-uuid="type"]')
    HASH_BADGE = (By.CSS_SELECTOR, '[data-uuid="status"]')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    RIGHT_SIDEBAR_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p')
    RIGHT_SIDEBAR_HASH_NAME = (By.CSS_SELECTOR, '.grid-pr-20px > h1')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar__button-wrap > div > button')
    RIGHT_SIDEBAR_EXPORT_BUTTON = (By.CSS_SELECTOR, '.sidebar__button-wrap > div > button:last-of-type')
    RIGHT_SIDEBAR_INDEX_BUTTON = (By.CSS_SELECTOR, '.sidebar__button-wrap > button')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')
    IMAGE_UPLOAD = (By.CSS_SELECTOR, '.notification > div:nth-child(2)')
    IMAGE_UPLOAD_PROCESS = (By.CSS_SELECTOR, '.notification > div:nth-child(3)')
    IMAGE_CANCEL = (By.CSS_SELECTOR, '.notification > div')
    NO_RESULTS = (By.CSS_SELECTOR, 'tbody > tr > td > div')
    WORKSPACE = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div > button')
    WORKSPACE_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div > button:nth-child(2)')
    FILES = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(2) > button')
    FILES_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(2) > button:nth-child(2)')
    MAP = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(4) > button')
    MAP_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(4) > button:nth-child(2)')
    EXPORT_FORM = (By.CSS_SELECTOR, '.modal-header')


class TagsLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    TAG_NAME = (By.CSS_SELECTOR, '#name')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    SEARCH = (By.CSS_SELECTOR, '#search')
    GRID_TAG = (By.CSS_SELECTOR, '[data-uuid="name"]')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    RIGHT_SIDEBAR_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p')
    RIGHT_SIDEBAR_NOCASES = (By.CSS_SELECTOR, '.tab-content > div > div')
    RIGHT_SIDEBAR_TAG_NAME = (By.CSS_SELECTOR, '.grid-pr-20px > h1')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar-filters > div > .btn.btn-primary')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')
    OPEN_BUTTON = (By.CSS_SELECTOR, '.button-open')
    WORKSPACE = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div > button')
    WORKSPACE_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div > button:nth-child(2)')
    FILES = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(2) > button')
    FILES_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(2) > button:nth-child(2)')
    CONTACTS = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(3) > button')
    CONTACTS_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) '
                                     '> div:nth-child(3) > button:nth-child(2)')
    MAP = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(4) > button')
    MAP_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(4) > button:nth-child(2)')


class KeywordsSetsLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    OPEN_BUTTON = (By.CSS_SELECTOR, '.button-open')
    KEYWORDSET_NAME = (By.CSS_SELECTOR, '#name')
    KEYWORDSET_NOTE = (By.CSS_SELECTOR, '#note')
    KEYWORDSET_UPLOAD = (By.CSS_SELECTOR, '#fileDropRef')
    KEYWORDSET_TYPE = (By.CSS_SELECTOR, '#format')
    KEYWORDSET_EXTENSION = (By.CSS_SELECTOR, '#type')
    KEYWORDSET_EXPORT = (By.CSS_SELECTOR, '.modal-footer.justify-content-end > button:nth-child(2)')
    KEYWORDSET_ADD_WORD = (By.CSS_SELECTOR, '#popup-dictionary__add-word')
    KEYWORDSET_ADD = (By.CSS_SELECTOR, '[title="Add to keyword set"]')
    KEYWORDSET_ENCODING = (By.CSS_SELECTOR, '#encoding')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    SEARCH = (By.CSS_SELECTOR, '#search')
    GRID_KEYWORDSET = (By.CSS_SELECTOR, '[data-uuid="name"]')
    GRID_KEYWORDSET_TYPE = (By.CSS_SELECTOR, '[data-uuid="dClass"]')
    GRID_KEYWORDSET_NOTE = (By.CSS_SELECTOR, '[data-uuid="note"]')
    GRID_GENERAL_CHECKBOX = (By.CSS_SELECTOR, '[data-uuid="checkbox"] > app-grid-checkbox-dictionary > label > span')
    KEYWORDSET_BADGE = (By.CSS_SELECTOR, '[data-uuid="status"]')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    RIGHT_SIDEBAR_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p')
    RIGHT_SIDEBAR_KEYWORDSET_NAME = (By.CSS_SELECTOR, '.grid-pr-20px > h1')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar__button-wrap > div > button')
    RIGHT_SIDEBAR_EXPORT_BUTTON = (By.CSS_SELECTOR, '.sidebar__button-wrap > div > button:last-of-type')
    RIGHT_SIDEBAR_INDEX_BUTTON = (By.CSS_SELECTOR, '.sidebar__button-wrap > button')
    RIGHT_SIDEBAR_CONTENT_TAB = (By.CSS_SELECTOR, '[role="tablist"] > li:nth-child(2)')
    RIGHT_SIDEBAR_CONTENT_TAB_NODATA = (By.CSS_SELECTOR, '.tab-content > div:nth-child(2) > div')
    RIGHT_SIDEBAR_CONTENT_TAB_1ST_WORD = (By.CSS_SELECTOR, '.sidebar-meta.sidebar-meta_indented.p-0 > div')
    RIGHT_SIDEBAR_CONTENT_TAB_2ND_WORD = (By.CSS_SELECTOR, '.sidebar-meta.sidebar-meta_indented.p-0 > div:nth-child(2)')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')
    IMAGE_UPLOAD = (By.CSS_SELECTOR, '.notification > div:nth-child(2)')
    IMAGE_UPLOAD_PROCESS = (By.CSS_SELECTOR, '.notification > div:nth-child(3)')
    IMAGE_CANCEL = (By.CSS_SELECTOR, '.notification > div')
    NO_RESULTS = (By.CSS_SELECTOR, 'tbody > tr > td > div')
    WORKSPACE = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div > button')
    WORKSPACE_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div > button:nth-child(2)')
    FILES = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(2) > button')
    FILES_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(2) > button:nth-child(2)')
    CONTACTS = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(3) > button')
    CONTACTS_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > '
                                     'div:nth-child(2) > div:nth-child(3) > button:nth-child(2)')
    MAP = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(4) > button')
    MAP_TAB = (By.CSS_SELECTOR, 'app-popup-go-to > div > div:nth-child(2) > div:nth-child(4) > button:nth-child(2)')
    EXPORT_FORM = (By.CSS_SELECTOR, '.modal-header')


class WatchListsLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')


class WorkspaceLocators:
    TAG_RIGHT_SIDEBAR = (By.CSS_SELECTOR, '.sidebar-tag__list')
    TAG_FILTER = (By.CSS_SELECTOR, 'app-workspace-aside > div:nth-child(5) > .tree__root:nth-child(6) '
                                   '> div > div:nth-child(2) > div:nth-child(1)')
    TAG_1ST = (By.CSS_SELECTOR, 'app-workspace-aside > div:nth-child(5) > .tree__root:nth-child(6) > '
                                'div:nth-child(2) >  div:nth-child(2) > div > label > div:nth-child(2) > d')
    COUNTER = (By.CSS_SELECTOR, '.align-items-center.col-5 > h1')
    LOAD_WAIT = (By.CSS_SELECTOR, '.table__data-not-found > td > div')
    LEFT_SIDEBAR = (By.CSS_SELECTOR, '[appsidebartarget="left"]')


class FilesLocators:
    COUNTER = (By.CSS_SELECTOR, '.align-items-center.col-5 > h1')
    LOAD_WAIT = (By.CSS_SELECTOR, '.table__data-not-found > td > div')


class ContactsLocators:
    COUNTER = (By.CSS_SELECTOR, '.align-items-center.col-5 > h1')
    LOAD_WAIT = (By.CSS_SELECTOR, '.table__data-not-found > td > div')


class MapLocators:
    COUNTER = (By.CSS_SELECTOR, '.map-total-label')


class AdminLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    ADD_SECTION = (By.CSS_SELECTOR, '.modal-header')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    NOTIFI_OK = (By.CSS_SELECTOR, '.modal-footer > div > .btn.btn-primary')
    CANCEL_BUTTON = (By.CSS_SELECTOR, '.modal-footer.justify-content-end > button')
    LOGIN_FIELD = (By.CSS_SELECTOR, '#login')
    SELECT_STATUS = (By.CSS_SELECTOR, '#status')
    FIRST_NAME = (By.CSS_SELECTOR, '#firstName')
    LAST_NAME = (By.CSS_SELECTOR, '#lastName')
    PASSWORD_FIELD = (By.CSS_SELECTOR, '#password')
    PASSWORD_COPY_FIELD = (By.CSS_SELECTOR, '#passwordCopy')
    BASKET = (By.CSS_SELECTOR, '[data-uuid="delete"]')
    SEARCH = (By.CSS_SELECTOR, '[name="search"]')
    BASKET_YES_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')
    BASKET_MESSAGE = (By.CSS_SELECTOR, '[class="py-2"]')
    ADMIN_IN_TABLE = (By.XPATH, '//span[text()="Login12"]')
    EXPERT_IN_TABLE = (By.XPATH, '//span[text()="Login12_ex"]')
    LOAD_IN_TABLE = (By.XPATH, '//span[text()="Login12_load"]')
    SELECTED_LINE = (By.CSS_SELECTOR, '.table__row--selected')
    GRID_LOGIN = (By.CSS_SELECTOR, '[data-uuid="login"]')
    GRID_STATUS = (By.CSS_SELECTOR, '[data-uuid="status"]')
    GRID_FNAME = (By.CSS_SELECTOR, '[data-uuid="firstName"]')
    GRID_LNAME = (By.CSS_SELECTOR, '[data-uuid="lastName"]')
    GRID_SORT_LOGIN = (By.CSS_SELECTOR, '.styled.table--border > thead > tr > th')
    GRID_SORT_STATUS = (By.CSS_SELECTOR, '.styled.table--border > thead > tr > th:nth-child(2)')
    GRID_SORT_NAME = (By.CSS_SELECTOR, '.styled.table--border > thead > tr > th:nth-child(3)')
    GRID_SORT_LASTNAME = (By.CSS_SELECTOR, '.styled.table--border > thead > tr > th:nth-child(4)')
    GRID_SORT_POSITION = (By.CSS_SELECTOR, '.styled.table--border > thead > tr > th:nth-child(5)')
    GRID_1ST_ROW = (By.CSS_SELECTOR, 'tbody > tr:nth-child(1)')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    REG_NOTIFI = (By.CSS_SELECTOR, '.py-2')
    CASE_RIGHTS = (By.CSS_SELECTOR, '[for="rights"] > span')
    CASES_1ST_CASE = (By.CSS_SELECTOR, '#popup-user__cases > div > div.kit__content > label')
    CASES_2ND_CASE = (By.CSS_SELECTOR, '#popup-user__cases > div > div.kit__content > label:nth-child(2)')
    CASES_3RD_CASE = (By.CSS_SELECTOR, '#popup-user__cases > div > div.kit__content > label:nth-child(3)')
    CASES_CHECKBOX = (By.CSS_SELECTOR, '#popup-user__cases > div > div > label > span')
    CASES_SEARCH = (By.CSS_SELECTOR, '#casesFormSearch')
    SORT_CASES = (By.CSS_SELECTOR, '#popup-user__cases > div > div > .kit__action')
    DEPARTMENTS_1ST_DEP = (By.CSS_SELECTOR, 'app-list-departments > div > div:nth-child(2) > label')
    DEPARTMENTS_CHECKBOX = (By.CSS_SELECTOR, 'app-list-departments > div > div > label > span')
    DEPARTMENTS_SEARCH = (By.CSS_SELECTOR, '#departmentsFormSearch')
    RIGHT_SIDEBAR_DEPARTMENT = (By.CSS_SELECTOR, '.nav-tabs.nav > li:nth-child(2)')
    RIGHT_SIDEBAR_DEPARTMENT_NAME = (By.CSS_SELECTOR, '.tab-pane.fade.active.show > div > div')
    RIGHT_SIDEBAR_NO_DEPARTMENTS = (By.CSS_SELECTOR, '.flex-scroll.grid-pr-15px > div > div > div > div> div')
    RIGHT_SIDEBAR_NO_CASES = (By.CSS_SELECTOR, '.flex-scroll.grid-pr-15px > div > div > div > div> div')
    RIGHT_SIDEBAR_CASE = (By.CSS_SELECTOR, '.nav-tabs.nav > li:nth-child(3)')
    RIGHT_SIDEBAR_CASE_NAME = (By.CSS_SELECTOR, '.tab-pane.fade.active.show > div > div')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar-filters > div > .btn.btn-primary')
    RIGHT_SIDEBAR_FIRST_NAME = (By.CSS_SELECTOR, '[role="tabpanel"] > div > div:nth-child(4) > .meta__content')
    RIGHT_SIDEBAR_LAST_NAME = (By.CSS_SELECTOR, '[role="tabpanel"] > div > div:nth-child(5) > .meta__content')
    CHANGE_PASSWORD = (By.CSS_SELECTOR, '.typography--text-underline.cursor-pointer')
    DEACTIVATE_ACCOUNT = (By.CSS_SELECTOR, '[for="disabled"] > span')


class DepartmentsLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, '.btn-add')
    ADD_SECTION = (By.CSS_SELECTOR, '.modal-header')
    FINAL_ADD = (By.CSS_SELECTOR, '.modal-footer > .btn.btn-primary')
    CANCEL_BUTTON = (By.CSS_SELECTOR, '.modal-footer.justify-content-end > button')
    DEPARTMENT_NAME = (By.CSS_SELECTOR, '#name')
    DEPARTMENT_NOTE = (By.CSS_SELECTOR, '#note')
    CASES_SEARCH = (By.CSS_SELECTOR, '#casesFormSearch')
    USERS_SEARCH = (By.CSS_SELECTOR, '#usersFormSearch')
    USERS_1ST = (By.CSS_SELECTOR, 'app-list-users > div > div:nth-child(2) > label')
    USERS_2ND = (By.CSS_SELECTOR, 'app-list-users > div > div:nth-child(2) > label:nth-child(2)')
    USERS_3RD = (By.CSS_SELECTOR, 'app-list-users > div > div:nth-child(2) > label:nth-child(3)')
    CASES_1ST = (By.CSS_SELECTOR, '.col-4:nth-child(3) > div > div:nth-child(2) > label > span:nth-child(2)')
    CASES_2ND = (
        By.CSS_SELECTOR, '.col-4:nth-child(3) > div > div:nth-child(2) > label:nth-child(2) > span:nth-child(2)')
    SORT_USERS = (By.CSS_SELECTOR, 'app-list-users > div > div > div:nth-child(3) > button')
    SORT_CASES = (By.CSS_SELECTOR, '.col-4:nth-child(3) > div > div > div:nth-child(3) > button')
    GENERAL_CHECKBOX_USERS = (By.CSS_SELECTOR, 'app-list-users > div > div > label > span')
    GENERAL_CHECKBOX_CASES = (By.CSS_SELECTOR, '.col-4:nth-child(3) > div > div > label > span')
    RIGHT_SIDEBAR_TOP_DEPARTMENT_NAME = (By.CSS_SELECTOR, '.grid-pr-20px > h1')
    RIGHT_SIDEBAR_DEPARTMENT = (By.CSS_SELECTOR, '.nav-tabs.nav > li:nth-child(1)')
    RIGHT_SIDEBAR_DEPARTMENT_NAME = (By.CSS_SELECTOR, '.tab-pane.fade.active.show > div > div > div:nth-child(2)')
    RIGHT_SIDEBAR_USERS = (By.CSS_SELECTOR, '.nav-tabs.nav > li:nth-child(2)')
    RIGHT_SIDEBAR_NOUSERS = (By.CSS_SELECTOR, '.tab-pane > div')
    RIGHT_SIDEBAR_USER_NAME_1ST = (By.CSS_SELECTOR, '.tab-pane > label > span > span:nth-child(2)')
    RIGHT_SIDEBAR_USER_NAME_2ND = (By.CSS_SELECTOR, '.tab-pane > label:nth-child(2) > span > span:nth-child(2)')
    RIGHT_SIDEBAR_CASES = (By.CSS_SELECTOR, '.nav-tabs.nav > li:nth-child(3)')
    RIGHT_SIDEBAR_CASES_NAME = (By.CSS_SELECTOR, '.tab-pane.fade.active.show > label')
    RIGHT_SIDEBAR_NOCASES = (By.CSS_SELECTOR, '.tab-pane.fade.active.show > div')
    RIGHT_SIDEBAR_EDIT_BUTTON = (By.CSS_SELECTOR, '.sidebar-filters > div > .btn.btn-primary')
    RIGHT_SIDEBAR_USERS_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p')
    RIGHT_SIDEBAR_CASES_COUNTER = (By.CSS_SELECTOR, '.grid-pr-20px > p:nth-child(3)')
    RIGHT_SIDEBAR_CASE_NAME_1ST = (By.CSS_SELECTOR, '.tab-pane > label > span > span:nth-child(2)')
    RIGHT_SIDEBAR_CASE_NAME_2ND = (By.CSS_SELECTOR, '.tab-pane > label:nth-child(2) > span > span:nth-child(2)')
    SEARCH = (By.CSS_SELECTOR, '[name="search"]')
    COUNTER = (By.CSS_SELECTOR, '.d-flex > h1')
    GRID_DEPARTMENT_NAME = (By.CSS_SELECTOR, '[data-uuid="name"]')
    GRID_DEPARTMENT_NOTE = (By.CSS_SELECTOR, '[data-uuid="note"]')
    GRID_DEPARTMENT_BUCKET = (By.CSS_SELECTOR, '.grid-delete')
    GRID_NO_RESULTS = (By.CSS_SELECTOR, '.table__data-not-found > td > div')
    DELETE_CONFIRM = (By.CSS_SELECTOR, 'app-popup-confirm-action')
    YES_BUCKET_BUTTON = (By.CSS_SELECTOR, '.btn.btn-danger')


class LoginLocators:
    LOGIN_FIELD = (By.CSS_SELECTOR, '#login')
    PASSWORD_FIELD = (By.CSS_SELECTOR, '#password')
    LOGIN_BUTTON = (By.CSS_SELECTOR, '#loginButton')
    NOTIFICATION = (By.CSS_SELECTOR, '.notification > div:nth-child(2)')
    EYE = (By.CSS_SELECTOR, '.password-control__btn')
    LOGIN_CARD = (By.CSS_SELECTOR, '.login__card')
    LOGIN_CARD_VERSION = (By.CSS_SELECTOR, '.align-items-center.row > div:nth-child(2)')
    LOGIN_CARD_LICENSE_NUM = (By.CSS_SELECTOR, '.version-info__value')
    LOGIN_CARD_LICENSE_DATE = (By.CSS_SELECTOR, '.text-muted > div:nth-child(2) > div:nth-child(2)')
